### ISSUE TITLE
buildMatrix function

### ISSUE THREAD

**Issue by abhishekolympics** [Sunchit/Coding-Decoded#456]
I am not able to understand BuildMatrix function what its doing. You also not explained it in your video. 

Can you guide me in right direction about what this function is doing.

**Comment by saorav21994** [comment]
@abhishekolympics The query is in reference to which question ?

**Comment by abhishekolympics** [comment]
SOLUTION=https://github.com/Sunchit/Coding-Decoded/blob/master/August2021/PalindromePartitioningII.java

QUESTION=https://leetcode.com/problems/palindrome-partitioning-ii/


VIDEO SOLUTION=https://www.youtube.com/watch?v=HUeUmrQy9cs

**Comment by Aditya1101999** [comment]
The buildMatrix function in the provided code is responsible for constructing a matrix dp of boolean values. This matrix is used to store whether a substring of the given string s is a palindrome or not.

The function takes two parameters:

s: The input string.
n: The length of the input string.
The matrix dp is initialized as a boolean array of size n by n. Each cell dp[i][j] represents whether the substring from index i to index j in the string s is a palindrome or not.

The function iterates over the indices of the matrix in a bottom-up manner. Starting from the last row and moving upwards, and within each row, it traverses from left to right.

At each cell dp[i][j], the function checks if the characters at indices i and j in the string s are the same. Additionally, it checks if the substring between i and j has a length of at most 2 or if the inner substring, excluding the first and last characters, is also a palindrome (dp[i + 1][j - 1] is true).

If both conditions are satisfied, the cell dp[i][j] is set to true, indicating that the corresponding substring is a palindrome.

Finally, the function returns the constructed matrix dp, which will be used in the minCut function to find the minimum number of cuts required to partition the given string s into palindromic substrings.

**Comment by abhishekolympics** [comment]
Thanks. Now I have a clear understanding of the function.

**Comment by Sunchit** [comment]
@abhishekolympics awesome, thanks for talking it up @Aditya1101999

**Comment by Aditya1101999** [comment]
No worries ,
Most welcome Sunchit
